# :noTabs=true:mode=yaml:tabSize=2:indentSize=2:
version: 2.1
jobs:
  build-and-bundle:
    macos:
      xcode: "9.4.1"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: ./bootstrap.sh
      - run: ./build.sh
      - run: ./bundle.sh
      - run: ./release.sh _build/gPodder.app $(git describe --tags)
      - run: ./release_deps.sh _build/gPodder.app $(git describe --tags)
      - run: rm -Rf _build/gPodder.app/
      - store_artifacts:
          path: /Users/distiller/project/_build
      - run: echo -e "$SSH_KEY" > /Users/distiller/project/gpodderbuild
      - run: chmod go-rwx /Users/distiller/project/gpodderbuild
      - run: if git describe --tags --exact-match 2>/dev/null; then rsync -e "ssh -p$RSYNC_PORT -i /Users/distiller/project/gpodderbuild -o StrictHostKeyChecking=no" -avrz "_home" "_build" "$RSYNC_HOME/$CIRCLE_BUILD_NUM/"; fi
      - run: rm /Users/distiller/project/gpodderbuild
  dummy:
    macos:
      xcode: "9.2.0"
    shell: /bin/bash --login -o pipefail
    steps:
     - checkout
     - run: ./bootstrap.sh

workflows:
  version: 2
  build-bundle:
    jobs:
      - build-and-bundle
